Testing GitHub action yaml file

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -31,9 +31,9 @@ jobs:
       # Run individual test for testing
       - name: Run individual test
         run: |
-        docker-compose -f docker-compose.yml exec -T underpass sh -c "/code/build/src/testsuite/libunderpass.all/yaml-test"
-        exit_code=$?
-        if [ $exit_code -ne 0 ]; then
-          echo "Test failed with exit code $exit_code"
-          exit $exit_code
-        fi
+          docker-compose -f docker-compose.yml exec -T underpass sh -c "/code/build/src/testsuite/libunderpass.all/yaml-test"
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Test failed with exit code $exit_code"
+            exit $exit_code
+          fi
