Revert "Merge: Optimise dockerfiles, fix ci, release images"

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,10 +1,7 @@
-name: 🧪 Build and Test
+name: 🧪 Build and test
 
 on:
   push:
-    branches:
-      - master
-  pull_request:
     branches:
       - master
     paths:
@@ -13,13 +10,20 @@ on:
       - docker/**
 
 jobs:
-  build-and-test:
-    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@1.2.1
-    with:
-      image_name: ghcr.io/${{ github.repository }}
-      build_dockerfile: docker/underpass.dockerfile
-      compose_service: underpass
-      compose_command: echo "Tests complete."
-      # TODO update postgis image to use github repo var ${{ vars.POSTGIS_TAG }}
-      cache_extra_imgs: |
-        "docker.io/postgis/postgis:15-3.3-alpine"
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      # Relies on the master branch built docker image for build-deps
+      - name: Start Docker Compose & build
+        run: cd docker && docker-compose up -d underpass
+      # Build and run tests
+      - name: Build and run tests 
+        run: |
+          docker-compose -f docker-compose.yml exec -T underpass sh -c "cd /code/build && make check -j `nproc`"
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Test failed with exit code $exit_code"
+            exit $exit_code
+          fi
